name: Python-CI

on:
    push:
        branches:
            - main

jobs:
    Clone-Repo:
        name: Clone Repo
        runs-on: ubuntu-latest

        steps:
           - name: Checkout Repo
             uses: actions/checkout@v3

           - name: Upload Repo
             uses: actions/upload-artifact@v3
             with:
                name: code
                path: .

    Use-Flake8:
      runs-on: ubuntu-latest

      needs: Clone-Repo

      steps:
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.12.0

        - name: Download Code
          uses: actions/download-artifact@v3
          with:
            name: code
            path: .

        - name: Install flake8
          run: pip install flake8
        - name: Run flake8
          uses: py-actions/flake8@v2
          with:
            checkName: 'Use-Flake8'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    Run-Python-Tests:
        name: Run Python Tests
        runs-on: ubuntu-latest

        needs: Clone-Repo

        steps:
          - name: Download Code
            uses: actions/download-artifact@v3
            with:
              name: code
              path: .

          - name: Install dependencies
            run: |
              cd src/
              python3 -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Run Tests
            run: python -m unittest app_test.py

    Scan-With-SonarCloud:
        name: Scan with SonarCloud
        runs-on: ubuntu-latest

        needs: Clone-Repo

        steps:
            - name: Download Code
              uses: actions/download-artifact@v3
              with:
                name: code
                path: .

            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

    Scan-With-Snyk:
      name: Scan with Snyk
      runs-on: ubuntu-latest

      needs: Clone-Repo

      steps:
        - name: Download Code
          uses: actions/download-artifact@v3
          with:
            name: code
            path: .

        - name: Install Python
          run: sudo apt-get update -y && sudo apt-get install -y python3 python3-pip

        - name: Install Dependencies
          run: pip install -r src/requirements.txt

        - name: Setup Snyk
          uses: snyk/actions/setup@master

        - name: Run Snyk
          run: snyk test --file=src/requirements.txt
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    Create-Docker-Image:
        name: Create Docker Image
        runs-on: ubuntu-latest

        needs: [Use-Flake8, Run-Python-Tests, Scan-With-SonarCloud, Scan-With-Snyk]

        steps:
            - name: Download Code
              uses: actions/download-artifact@v3
              with:
                name: code
                path: .

            - name: Build Image
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-work:${{ github.sha }} .

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: 'docker.io/${{ secrets.DOCKER_USERNAME }}/devops-work:${{ github.sha }}'
                format: 'table'
                exit-code: '1'
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'CRITICAL,HIGH'

            - name: Login to DockerHub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            - name: Upload Image
              run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-work:${{ github.sha }}
