name: Python-CI

on: push

jobs:
    Clone-Repo:
        name: Clone Repo
        runs-on: ubuntu-latest

        steps:
           - name: Checkout Repo
             uses: actions/checkout@v4
           
           - name: Upload Repo
             uses: actions/upload-artifact@v4
             with:
                name: code
                path: .

    Create-Docker-Image:
        name: Create Docker Image
        runs-on: ubuntu-latest

        needs: Clone-Repo

        steps:
            - name: Download Code
              uses: actions/download-artifact@v4
              with:
                name: code
                path: .

            - name: Login to DockerHub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_USERNAME }}
            
            - name: Build Image
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-work:latest

            - name: Upload Image
              run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-work:latest

            